/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import gestores.GestorArticulo;
import gestores.GestorCompra;
import gestores.GestorProveedor;
import gestores.GestorUsuario;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Articulo;
import modelo.Compra;
import modelo.Proveedor;
import modelo.CompraLinea;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.codehaus.groovy.tools.shell.Main;
import proyectociber.ProyectoCiber;
import reportes.JDialogImpresion;
/**
 *
 * @author abel
 */
public class VentanaCompra extends javax.swing.JDialog {
    /**
     * Creates new form VentanaCompra
     */
   
    public VentanaCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
        mostrarlineas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbltotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblpreciocompra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblrazonsocial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcuit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        lbltotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltotal.setText("Total:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Total:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Articulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Codigo de Barra:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        lblcodigo.setForeground(new java.awt.Color(0, 0, 255));
        lblcodigo.setText("Codigo de Barra:");
        jPanel2.add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 30, -1, -1));

        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lblnombre.setForeground(new java.awt.Color(0, 0, 255));
        lblnombre.setText("Nombre:");
        jPanel2.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 30, -1, -1));

        jLabel7.setText("Descripcion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 80, -1, -1));

        lbldescripcion.setForeground(new java.awt.Color(0, 0, 255));
        lbldescripcion.setText("Descripcion:");
        jPanel2.add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 80, -1, -1));

        jLabel8.setText("Precio Compra:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        lblpreciocompra.setForeground(new java.awt.Color(0, 0, 255));
        lblpreciocompra.setText("Precio Compra:");
        jPanel2.add(lblpreciocompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 80, -1, -1));

        jLabel9.setText("Cantidad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, -1, -1));
        jPanel2.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 112, 58, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 30, 70, 60));

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 112, 140, 47));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Razon Social:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, -1, -1));

        lblrazonsocial.setForeground(new java.awt.Color(0, 0, 255));
        lblrazonsocial.setText("Razon Social:");
        jPanel1.add(lblrazonsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 38, -1, -1));

        jLabel2.setText("CUIT:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 38, -1, -1));

        lblcuit.setForeground(new java.awt.Color(0, 0, 255));
        lblcuit.setText("CUIT:");
        jPanel1.add(lblcuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 38, -1, -1));

        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 83, -1, -1));

        lbltelefono.setForeground(new java.awt.Color(0, 0, 255));
        lbltelefono.setText("Telefono:");
        jPanel1.add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 83, -1, -1));

        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 83, -1, -1));

        lblmail.setForeground(new java.awt.Color(0, 0, 255));
        lblmail.setText("Email:");
        jPanel1.add(lblmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 83, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 30, 70, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 47));

        jButton5.setText("Borrar Linea");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 47));

        jButton6.setText("Guardar ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 47));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(32, 32, 32)
                                .addComponent(lbltotal)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 VentanaBuscarProveedor v = new VentanaBuscarProveedor(this, true);
            v.setVisible(true);
            if(v.getAceptado()==1){
                proveedor.setId(v.getId());
                gestorProveedor.recuperar(proveedor);
                lblmail.setText(proveedor.getMail());
                lblrazonsocial.setText(proveedor.getRazonSocial());
                lbltelefono.setText(proveedor.getTelefono());
                lblcuit.setText(proveedor.getCuit());
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(lblrazonsocial.getText().equals("-"))JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor");
        else{
   VentanaBuscarArticuloCompra v = new VentanaBuscarArticuloCompra(this, true);
   v.setVisible(true);
   if(v.getAceptado()==1){
   articulo.setId(v.getId());
   gestorArticulo.recuperar(articulo);
   lblcodigo.setText(articulo.getCodBarra());
   lblnombre.setText(articulo.getNombre());
   lbldescripcion.setText(articulo.getDescripcion());
   lblpreciocompra.setText(String.valueOf(articulo.getPrecioCompra()));
   
   txtcantidad.setText("1");
   txtcantidad.requestFocus();
   }}      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(lblrazonsocial.getText().equals("-"))JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor");
        else if(lbldescripcion.getText().isEmpty())JOptionPane.showMessageDialog(this, "debe seleccionar un articulo");
        else if(txtcantidad.getText().isEmpty())JOptionPane.showMessageDialog(this, "Debe ingresar la cantidad");
        //else  if(lblnombre.getText().isEmpty())JOptionPane.showMessageDialog(this, "Debe ingresar un articulo");
        else{
                
        int cantidad = Integer.parseInt(txtcantidad.getText());
     if(cantidad <1){JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero");}
       else{
           gestorCompra.agregarLinea(compra, articulo, cantidad);
           limpiararticulo();
           mostrarlineas();
          }
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased

    }//GEN-LAST:event_tablaMouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int fila = tabla.getSelectedRow();
    if(fila==-1)JOptionPane.showMessageDialog(this, "Debe seleccionar una linea");
    else
    {
        gestorCompra.borrarLinea(compra, fila);
        mostrarlineas();
    }      
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
       if(lblrazonsocial.getText().equals("-"))JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor");
       else if(tabla.getRowCount()==0)JOptionPane.showMessageDialog(this, "Debe agregar al menos una linea ");
       else{
        
    compra.setProveedor(proveedor);
    compra.setFecha(new java.util.Date());
    compra.setEmpleado(GestorUsuario.logeado.getEmpleado());    
    gestorCompra.agregar(compra);
    limpiar();
    mostrarlineas();
    if(JOptionPane.showConfirmDialog(this, "Desea imprimir el comprobante","Confirme",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    {imprimir();
    }
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int r = JOptionPane.showConfirmDialog(this, "Desea cancelar la compra","Confirme",JOptionPane.YES_NO_OPTION);
    if(r==JOptionPane.YES_OPTION)
    {
        compra.getLista().clear();
        limpiar();
        mostrarlineas();
    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCompra dialog = new VentanaCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcuit;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpreciocompra;
    private javax.swing.JLabel lblrazonsocial;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
private GestorProveedor gestorProveedor = new GestorProveedor();
private Proveedor proveedor = new Proveedor();

private GestorArticulo gestorArticulo = new GestorArticulo();
private Articulo articulo = new Articulo();

private GestorCompra gestorCompra = new GestorCompra();        
private Compra compra = new Compra();

private void limpiarproveedor(){

lblrazonsocial.setText("-");
lblcuit.setText("-");
lbltelefono.setText("-");
lblmail.setText("-");

}

private void limpiar(){
limpiarproveedor();
limpiararticulo();

}

    private void limpiararticulo() {
        lblcodigo.setText("");
        lblnombre.setText("");
        lbldescripcion.setText("");
        lblpreciocompra.setText("");
        
        //lbl.setText("");
        
    }
 private void mostrarlineas() {
      DefaultTableModel matriz = new DefaultTableModel();
        matriz.addColumn("Id");
        matriz.addColumn("Codigo");
        matriz.addColumn("Nombre");
        matriz.addColumn("Descripcion");
        matriz.addColumn("Precio Compra");
        matriz.addColumn("Cantidad");
        matriz.addColumn("Subtotal");
       
       
        ArrayList<CompraLinea> lista = compra.getLista();
                for (CompraLinea a : lista) {
            matriz.addRow(new Object[]{ 
                a.getId(),
                a.getArticulo().getCodBarra(),
                a.getArticulo().getNombre(),
                a.getArticulo().getDescripcion(),
                a.getArticulo().getPrecioCompra(),
                a.getCantidad(),
                a.getArticulo().getPrecioCompra()*a.getCantidad()
               
            });
        }
        tabla.setModel(matriz); 
        // tengo que cambiar por 
        // compra.calculartotal()........
        compra.calculartotal();
        lbltotal.setText("$"+compra.getTotal());
      //  lbliva.setText("$"+venta.getIva());
       // lblgrantotal.setText("$"+venta.getGranTotal());
  
}

    private void imprimir() {
        
       ProyectoCiber cn = new ProyectoCiber();
         Map parameters = new HashMap();
           parameters.put("Id",compra.getId());
           
            String REPORTE ="C:\\Users\\abel\\Documents\\NetBeansProjects\\ProyectoCiber\\src\\reportes\\Compra.jrxml";
            
      try{
                JasperReport jasperReport =JasperCompileManager.compileReport(REPORTE);
                
                JasperPrint jasperPrint   =JasperFillManager.fillReport(jasperReport, parameters, cn.getConexion());
                JRViewer jrv=new JRViewer(jasperPrint);
            JDialogImpresion j;
            j = new JDialogImpresion(this,jrv);
           
            j.setVisible(true);
            
            }catch(JRException d){
                d.printStackTrace();
            }
            
//        try {
//            jr= (JasperReport) JRLoader.loadObjectFromFile(path);
//            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, cn.getConexion());
//           
//         JasperViewer  jv = new JasperViewer(jp);
//         JDialogImpresion j;
//                j = new JDialogImpresion(this,jv);
//            j.setVisible(true);
//         jv.setTitle("REPORTE DE COMPRA");
//      
//            
//        } catch (JRException ex) {
//            Logger.getLogger(VentanaCompra.class.getName()).log(Level.SEVERE, null, ex);
//        }
           
           
     
    }

      
   
}
    



